### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/osqp-ruby#1]
Plan

- [x] Convert P to upper triangle when needed
- [ ] Add `update` and `update_settings` methods
- [x] Support sparse matrices

**Comment by ak131554** [comment]
Hi,

is there any possibility, that we can expect support of sparse matrices in the near future? It would be sufficient (or a first step) to have the option to call the solver with the vectors in CSC format.

I've a rather large system to solve and I would prefer to not allocate memory for such large dimensional matrices. In the meantime, I succeeded to inherit from your solver to make it accept CSC matrices. But this seems to be rather a hack to me.

**Comment by ankane** [comment]
Hey @ak131554, just added support for COO matrices in bcc29437abbf1183f2ed06f334fdf335674ab2d3. Can you share how you're building and passing matrices in your version?

**Comment by ak131554** [comment]
> Hey @ak131554, just added support for COO matrices in [bcc2943](https://github.com/ankane/osqp-ruby/commit/bcc29437abbf1183f2ed06f334fdf335674ab2d3). Can you share how you're building and passing matrices in your version?

It's just a short proof of concept. I've copied part of your code and changed the setup method to accept all necessary arguments. Then I've changed method csc_matrix to just set `cx`, `ci` and `cp` instead of calculating those vectors.
```
class MySolver < OSQP::Solver
  def setup(pm, pn, px, pi, pp, q, am, an, ax, ai, ap, l, u, **settings)
    # settings
    set = create_settings(settings)

    # ensure bounds within OSQP infinity
    l = l.map { |v| v < -OSQP::FFI::OSQP_INFTY ? -OSQP::FFI::OSQP_INFTY : v }
    u = u.map { |v| v > OSQP::FFI::OSQP_INFTY ? OSQP::FFI::OSQP_INFTY : v }

    # data
    # do not assign directly to struct to keep refs
    p = csc_matrix(pm, pn, px, pi, pp)
    q = float_array(q)
    a = csc_matrix(am, an, ax, ai, ap)
    l = float_array(l)
    u = float_array(u)

    data = OSQP::FFI::Data.malloc
    data.n = an
    data.m = am
    data.p = p
    data.q = q
    data.a = a
    data.l = l
    data.u = u

    # work
    work = OSQP::FFI::Workspace.malloc
    check_result OSQP::FFI.osqp_setup(work.to_ptr.ref, data, set)
    @work = work
  end

  def csc_matrix(m, n, x, i, p)
    nnz = x.size
    cx = float_array(x)
    ci = int_array(i)
    cp = int_array(p)

    ptr = OSQP::FFI.csc_matrix(m, n, nnz, cx, ci, cp)
    # save refs
    ptr.instance_variable_set(:@osqp_refs, [cx, ci, cp])
    ptr
  end
end
```
Here, one must calculate the matrices in CSC format by himself/herself. And they have to ensure that the matrix P is an upper triangular matrix. Otherwise the underlying OSQP algorithm would raise an error.

**Comment by ak131554** [comment]
Hey @ankane. I've reviewed your implementation of COO and it looks good. But I've a suggestion. You should check the value in `def []=(row_index, column_index, value)` because in the present commit you can set zero there.

**Comment by ankane** [comment]
Thanks for sharing the code and the feedback. I've updated the zero handling. How are you constructing `cx`, `ci`, and `cp`?

**Comment by ak131554** [comment]
I've constructed them by hand. As I said, it was just a brief proof of concept that I can extend your solver so that I'm able to use sparse matrices instead of two-dimensional arrays.
Your approach to use COO and convert them into CSC is far better, because COO can easily be derived from my (in)equalities.

**Comment by ankane** [comment]
Great, just pushed a release with the new `Matrix` class.
